### ISSUE TITLE
What is wrong with this !add command? 

### ISSUE THREAD

**Issue by BananinhaWR** [TF2Autobot/tf2autobot#291] opened 2021-01-29 15:35 UTC
!add sku=31181;6;buy.metal=2.33;sell.metal=2.77
I want to add the killing tree, buying it for 2.33 ref and selling for 2.77 ref
My bot says this: 
![image](https://user-images.githubusercontent.com/46030774/106294032-70c5e580-622d-11eb-88c9-7434f8ec29b2.png)
idk which properties are missing or if I just wrote something wrong. Could someone write the right command and an explanation of why mine was wrong?

**Comment by idinium96** [comment] 2021-01-29 15:39
Duplicate of #290

**Closed by idinium96** 2021-01-29 15:39 UTC
Labels: duplicate
